# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 710)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("/* 1. Global Background and Text */\n"
"QMainWindow, QWidget {\n"
"    background-color: #121212; /* Deep dark grey/black */\n"
"    color: #E0E0E0; /* Off-white text for readability */\n"
"    font-family: \"Segoe UI\", \"Helvetica Neue\", sans-serif;\n"
"}\n"
"\n"
"/* 2. Layout Panels (Your QFrames) */\n"
"QFrame {\n"
"    background-color: #1E1E24; /* Slightly lighter grey for panels */\n"
"    border: 1px solid #2A2A35;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* 3. The Video Feed Label */\n"
"/* Assuming you name your camera label \"video_feed_label\" */\n"
"QLabel#video_feed_label {\n"
"    background-color: #000000;\n"
"    border: 2px solid #00F3FF; /* Neon Cyan tactical border */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* 4. Standard Text Labels (Telemetry data) */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* 5. Modern Interactive Buttons */\n"
"QPushButton {\n"
"    background-color: #2D2D3A;\n"
"    border: 1px solid #00F3FF; /* Cyan outline */\n"
"    color: #00F3FF; /* Cyan text */\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"    font: bold 11pt \"Ubuntu Sans\";\n"
"\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"/* Button Hover Animation */\n"
"QPushButton:hover {\n"
"    background-color: #00F3FF; /* Fill solid cyan on hover */\n"
"    color: #121212; /* Invert text to black */\n"
"}\n"
"\n"
"/* Button Click Animation */\n"
"QPushButton:pressed {\n"
"    background-color: #00B8D4;\n"
"    border: 1px solid #00B8D4;\n"
"}\n"
"\n"
"/* 6. The Console Output (Read-only text box) */\n"
"QTextEdit {\n"
"    background-color: #0A0A0C; /* Pitch black */\n"
"    color: #00FF41; /* Hacker terminal green */\n"
"    border: 1px solid #2A2A35;\n"
"    font-family: \"Courier New\", monospace;\n"
"    padding: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* General Text Labels (For titles like \"Battery\", \"Altitude\") */\n"
"QLabel {\n"
"    background-color: #1A1A24; /* Slightly lighter than the background */\n"
"    color: #A0A0B0; /* Muted grey/white text so it isn\'t blinding */\n"
"    padding: 6px 12px;\n"
"    border-radius: 4px;\n"
"    font-size: 13px;\n"
"    border-left: 3px solid #2A2A35; /* Subtle grey edge to give it structure */\n"
"}\n"
"\n"
"\n"
"/* 1. GroupBox Main Body (The Secret Fix) */\n"
"QGroupBox {\n"
"    color: #00F3FF;\n"
"    border: 1px solid #2A2A35;\n"
"    border-radius: 6px;\n"
"    margin-top: 25px; \n"
"    \n"
"    /* Apply the massive font to the WHOLE box so the title inherits it */\n"
"    font:  16pt \"Ubuntu Sans\"; \n"
"}\n"
"\n"
"/* 2. GroupBox Title Alignment */\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top left;\n"
"    padding: 0 8px; \n"
"    left: 1px; \n"
"    background-color: #1E1E24; \n"
"    /* Notice: No font commands here anymore! */\n"
"}\n"
"\n"
"/* 3. GroupBox Data Labels */\n"
"QGroupBox QLabel {\n"
"    /* Force the labels back down so they don\'t stay giant */\n"
"    font: 12pt \"Ubuntu Sans\";\n"
"    font-weight: normal; \n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_right = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_right.setMinimumSize(QtCore.QSize(291, 0))
        self.frame_right.setMaximumSize(QtCore.QSize(291, 16777215))
        self.frame_right.setBaseSize(QtCore.QSize(100, 0))
        self.frame_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame_right)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.dock_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.dock_button.setObjectName("dock_button")
        self.gridLayout_7.addWidget(self.dock_button, 0, 0, 1, 1)
        self.toggle_claw_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.toggle_claw_button.setObjectName("toggle_claw_button")
        self.gridLayout_7.addWidget(self.toggle_claw_button, 0, 1, 1, 1)
        self.radar_label = QtWidgets.QLabel(parent=self.groupBox)
        self.radar_label.setMinimumSize(QtCore.QSize(0, 40))
        self.radar_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.radar_label.setObjectName("radar_label")
        self.gridLayout_7.addWidget(self.radar_label, 1, 0, 1, 1)
        self.claw_current_label = QtWidgets.QLabel(parent=self.groupBox)
        self.claw_current_label.setMinimumSize(QtCore.QSize(0, 40))
        self.claw_current_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.claw_current_label.setObjectName("claw_current_label")
        self.gridLayout_7.addWidget(self.claw_current_label, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.frame_right)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.speak_button = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.speak_button.setObjectName("speak_button")
        self.verticalLayout_4.addWidget(self.speak_button)
        self.speak_status = QtWidgets.QLabel(parent=self.groupBox_2)
        self.speak_status.setMinimumSize(QtCore.QSize(0, 40))
        self.speak_status.setMaximumSize(QtCore.QSize(16777215, 40))
        self.speak_status.setObjectName("speak_status")
        self.verticalLayout_4.addWidget(self.speak_status)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.frame_right)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.co2_label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.co2_label.setMinimumSize(QtCore.QSize(0, 40))
        self.co2_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.co2_label.setObjectName("co2_label")
        self.gridLayout_5.addWidget(self.co2_label, 0, 0, 1, 1)
        self.vo2_label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.vo2_label.setMinimumSize(QtCore.QSize(0, 40))
        self.vo2_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.vo2_label.setObjectName("vo2_label")
        self.gridLayout_5.addWidget(self.vo2_label, 0, 1, 1, 1)
        self.hum_label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.hum_label.setMinimumSize(QtCore.QSize(0, 40))
        self.hum_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.hum_label.setObjectName("hum_label")
        self.gridLayout_5.addWidget(self.hum_label, 1, 0, 1, 1)
        self.temp_label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.temp_label.setMinimumSize(QtCore.QSize(0, 40))
        self.temp_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.temp_label.setObjectName("temp_label")
        self.gridLayout_5.addWidget(self.temp_label, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.frame_right, 0, 3, 1, 1)
        self.frame_center = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_center.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_center.setObjectName("frame_center")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_center)
        self.verticalLayout.setObjectName("verticalLayout")
        self.alert = QtWidgets.QLabel(parent=self.frame_center)
        self.alert.setMaximumSize(QtCore.QSize(16777215, 40))
        self.alert.setObjectName("alert")
        self.verticalLayout.addWidget(self.alert)
        self.video_frame = QtWidgets.QLabel(parent=self.frame_center)
        self.video_frame.setObjectName("video_frame")
        self.verticalLayout.addWidget(self.video_frame)
        self.log = QtWidgets.QTextEdit(parent=self.frame_center)
        self.log.setMinimumSize(QtCore.QSize(0, 50))
        self.log.setMaximumSize(QtCore.QSize(16777215, 180))
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout.addWidget(self.log)
        self.gridLayout_2.addWidget(self.frame_center, 0, 2, 1, 1)
        self.frame_left = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_left.setMinimumSize(QtCore.QSize(291, 0))
        self.frame_left.setMaximumSize(QtCore.QSize(291, 16777215))
        self.frame_left.setBaseSize(QtCore.QSize(100, 0))
        self.frame_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.telem_box = QtWidgets.QGroupBox(parent=self.frame_left)
        self.telem_box.setObjectName("telem_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.telem_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.battery_label = QtWidgets.QLabel(parent=self.telem_box)
        self.battery_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.battery_label.setBaseSize(QtCore.QSize(40, 0))
        self.battery_label.setObjectName("battery_label")
        self.gridLayout_3.addWidget(self.battery_label, 0, 0, 1, 1)
        self.current_label = QtWidgets.QLabel(parent=self.telem_box)
        self.current_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.current_label.setBaseSize(QtCore.QSize(40, 0))
        self.current_label.setObjectName("current_label")
        self.gridLayout_3.addWidget(self.current_label, 0, 1, 1, 1)
        self.altitude_label = QtWidgets.QLabel(parent=self.telem_box)
        self.altitude_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.altitude_label.setBaseSize(QtCore.QSize(40, 0))
        self.altitude_label.setObjectName("altitude_label")
        self.gridLayout_3.addWidget(self.altitude_label, 1, 0, 1, 1)
        self.velocity_label = QtWidgets.QLabel(parent=self.telem_box)
        self.velocity_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.velocity_label.setBaseSize(QtCore.QSize(40, 0))
        self.velocity_label.setObjectName("velocity_label")
        self.gridLayout_3.addWidget(self.velocity_label, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.telem_box, 4, 0, 1, 2)
        self.system_box = QtWidgets.QGroupBox(parent=self.frame_left)
        self.system_box.setObjectName("system_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.system_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.audio_alert_label = QtWidgets.QLabel(parent=self.system_box)
        self.audio_alert_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.audio_alert_label.setBaseSize(QtCore.QSize(40, 0))
        self.audio_alert_label.setObjectName("audio_alert_label")
        self.gridLayout_4.addWidget(self.audio_alert_label, 1, 1, 1, 1)
        self.video_alert_label = QtWidgets.QLabel(parent=self.system_box)
        self.video_alert_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.video_alert_label.setBaseSize(QtCore.QSize(40, 0))
        self.video_alert_label.setObjectName("video_alert_label")
        self.gridLayout_4.addWidget(self.video_alert_label, 1, 0, 1, 1)
        self.recording_label = QtWidgets.QLabel(parent=self.system_box)
        self.recording_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.recording_label.setBaseSize(QtCore.QSize(40, 0))
        self.recording_label.setObjectName("recording_label")
        self.gridLayout_4.addWidget(self.recording_label, 0, 1, 1, 1)
        self.armed_label = QtWidgets.QLabel(parent=self.system_box)
        self.armed_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.armed_label.setBaseSize(QtCore.QSize(40, 0))
        self.armed_label.setObjectName("armed_label")
        self.gridLayout_4.addWidget(self.armed_label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.system_box, 5, 0, 1, 2)
        self.ARM_button = QtWidgets.QPushButton(parent=self.frame_left)
        self.ARM_button.setObjectName("ARM_button")
        self.gridLayout.addWidget(self.ARM_button, 2, 0, 1, 1)
        self.HOLD_button = QtWidgets.QPushButton(parent=self.frame_left)
        self.HOLD_button.setObjectName("HOLD_button")
        self.gridLayout.addWidget(self.HOLD_button, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.app_logo = QtWidgets.QLabel(parent=self.frame_left)
        self.app_logo.setText("")
        self.app_logo.setPixmap(QtGui.QPixmap("img/drone.png"))
        self.app_logo.setScaledContents(True)
        self.app_logo.setObjectName("app_logo")
        self.verticalLayout_2.addWidget(self.app_logo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_app_title = QtWidgets.QLabel(parent=self.frame_left)
        self.label_app_title.setStyleSheet("/* Branding / App Title Styling */\n"
"QLabel {\n"
"    color: #00F3FF; /* Cyan to match your accent colors */\n"
"    font: bold 8pt \"Ubuntu Sans\";\n"
"    background-color: transparent; /* Ensures no weird boxes */\n"
"    border: none; /* Removes any default borders */\n"
"    border-top: 1px solid #2A2A35; /* Creates a subtle line separating the logo from the spacer */\n"
"    padding-top: 15px; /* Pushes the text down away from the line */\n"
"    padding-bottom: 5px;\n"
"    qproperty-alignment: AlignCenter; /* Forces the text perfectly to the center */\n"
"    letter-spacing: 2px; /* Spreads the letters out for a cinematic, high-tech look */\n"
"}")
        self.label_app_title.setObjectName("label_app_title")
        self.verticalLayout_2.addWidget(self.label_app_title)
        self.gridLayout_2.addWidget(self.frame_left, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 26))
        self.menubar.setObjectName("menubar")
        self.log_out = QtWidgets.QMenu(parent=self.menubar)
        self.log_out.setObjectName("log_out")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.log_out.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "CLAW"))
        self.dock_button.setText(_translate("MainWindow", "Dock"))
        self.toggle_claw_button.setText(_translate("MainWindow", "Toggle"))
        self.radar_label.setText(_translate("MainWindow", "Radar"))
        self.claw_current_label.setText(_translate("MainWindow", "Claw Current"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Voice"))
        self.speak_button.setText(_translate("MainWindow", "SPEAK"))
        self.speak_status.setText(_translate("MainWindow", "Status: Disabled"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Enviroment"))
        self.co2_label.setText(_translate("MainWindow", "CO2"))
        self.vo2_label.setText(_translate("MainWindow", "VO2"))
        self.hum_label.setText(_translate("MainWindow", "Humidity"))
        self.temp_label.setText(_translate("MainWindow", "Temp"))
        self.alert.setText(_translate("MainWindow", "Alert : Error 303. Please finish developing this application"))
        self.video_frame.setText(_translate("MainWindow", "video_frame"))
        self.log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Courier New\',\'monospace\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Log: </p></body></html>"))
        self.telem_box.setTitle(_translate("MainWindow", "TELEM"))
        self.battery_label.setText(_translate("MainWindow", "Battery"))
        self.current_label.setText(_translate("MainWindow", "Current Draw"))
        self.altitude_label.setText(_translate("MainWindow", "Altitude"))
        self.velocity_label.setText(_translate("MainWindow", "Velocity"))
        self.system_box.setTitle(_translate("MainWindow", "System Status"))
        self.audio_alert_label.setText(_translate("MainWindow", "Audio Alert"))
        self.video_alert_label.setText(_translate("MainWindow", "Video Alert"))
        self.recording_label.setText(_translate("MainWindow", "Recording"))
        self.armed_label.setText(_translate("MainWindow", "ARMED"))
        self.ARM_button.setText(_translate("MainWindow", "ARM"))
        self.HOLD_button.setText(_translate("MainWindow", "HOLD"))
        self.label_app_title.setText(_translate("MainWindow", "Drone Surveillance Application"))
        self.log_out.setTitle(_translate("MainWindow", "Log out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
